CREATE DATABASE IF NOT EXISTS SearchDB;


CREATE TABLE IF NOT EXISTS users(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(32) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL,
    isAdmin BOOLEAN NOT NULL DEFAULT(0)
);

CREATE TABLE IF NOT EXISTS logged(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idUser BIGINT NOT NULL,
    timeLogged TIMESTAMP,
    nameComputer VARCHAR(64)
);


CREATE TABLE IF NOT EXISTS meaningQuery(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    query VARCHAR(60) NOT NULL,
    typeLang VARCHAR(60) NOT NULL,
    meaning VARCHAR(256) NOT NULL,
    lastUserWhoModifiedTheField BIGINT NOT NULL
);


INSERT INTO users (userName, password, isAdmin) VALUES
('root','GyM8XFcqbkxs6qzd892RCA==',1)